// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositories

import (
	entities "capstone/entities"

	mock "github.com/stretchr/testify/mock"
)

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: comment
func (_m *CommentRepository) Create(comment entities.Comment) (entities.Comment, error) {
	ret := _m.Called(comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Comment) (entities.Comment, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(entities.Comment) entities.Comment); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(entities.Comment)
	}

	if rf, ok := ret.Get(1).(func(entities.Comment) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *CommentRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *CommentRepository) FindAll() ([]entities.Comment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Comment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Comment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByArticleID provides a mock function with given fields: id, page, limit
func (_m *CommentRepository) FindAllByArticleID(id uint, page int, limit int) ([]entities.Comment, int, error) {
	ret := _m.Called(id, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByArticleID")
	}

	var r0 []entities.Comment
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]entities.Comment, int, error)); ok {
		return rf(id, page, limit)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []entities.Comment); ok {
		r0 = rf(id, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) int); ok {
		r1 = rf(id, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uint, int, int) error); ok {
		r2 = rf(id, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *CommentRepository) FindByID(id uint) (entities.Comment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entities.Comment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) entities.Comment); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Comment)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: comment
func (_m *CommentRepository) Update(comment entities.Comment) (entities.Comment, error) {
	ret := _m.Called(comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Comment) (entities.Comment, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(entities.Comment) entities.Comment); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(entities.Comment)
	}

	if rf, ok := ret.Get(1).(func(entities.Comment) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentRepository creates a new instance of CommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepository {
	mock := &CommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
