// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositories

import (
	entities "capstone/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DonationRepository is an autogenerated mock type for the DonationRepository type
type DonationRepository struct {
	mock.Mock
}

// CreateLike provides a mock function with given fields: ctx, like
func (_m *DonationRepository) CreateLike(ctx context.Context, like entities.LikeDonationComment) error {
	ret := _m.Called(ctx, like)

	if len(ret) == 0 {
		panic("no return value specified for CreateLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.LikeDonationComment) error); ok {
		r0 = rf(ctx, like)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementLike provides a mock function with given fields: ctx, commentID
func (_m *DonationRepository) DecrementLike(ctx context.Context, commentID uint) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCode provides a mock function with given fields: code
func (_m *DonationRepository) GetByCode(code string) (entities.Donation, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Donation, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Donation); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(entities.Donation)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFundraisingID provides a mock function with given fields: id
func (_m *DonationRepository) GetByFundraisingID(id int) ([]entities.Donation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByFundraisingID")
	}

	var r0 []entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entities.Donation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []entities.Donation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Donation)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *DonationRepository) GetByID(id int) (entities.Donation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entities.Donation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entities.Donation); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Donation)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: limit, offset, userID
func (_m *DonationRepository) GetByUserID(limit int, offset int, userID uint) ([]entities.Donation, error) {
	ret := _m.Called(limit, offset, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, uint) ([]entities.Donation, error)); ok {
		return rf(limit, offset, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, uint) []entities.Donation); ok {
		r0 = rf(limit, offset, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Donation)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, uint) error); ok {
		r1 = rf(limit, offset, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentsByFundraisingID provides a mock function with given fields: id
func (_m *DonationRepository) GetCommentsByFundraisingID(id int) ([]entities.DonationComment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByFundraisingID")
	}

	var r0 []entities.DonationComment
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entities.DonationComment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []entities.DonationComment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.DonationComment)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementLike provides a mock function with given fields: ctx, commentID
func (_m *DonationRepository) IncrementLike(ctx context.Context, commentID uint) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsLiked provides a mock function with given fields: ctx, commentID, userID
func (_m *DonationRepository) IsLiked(ctx context.Context, commentID uint, userID uint) (bool, error) {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsLiked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, commentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, commentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveLike provides a mock function with given fields: ctx, commentID, userID
func (_m *DonationRepository) RemoveLike(ctx context.Context, commentID uint, userID uint) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: donation
func (_m *DonationRepository) Save(donation entities.Donation) (entities.Donation, error) {
	ret := _m.Called(donation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Donation) (entities.Donation, error)); ok {
		return rf(donation)
	}
	if rf, ok := ret.Get(0).(func(entities.Donation) entities.Donation); ok {
		r0 = rf(donation)
	} else {
		r0 = ret.Get(0).(entities.Donation)
	}

	if rf, ok := ret.Get(1).(func(entities.Donation) error); ok {
		r1 = rf(donation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveComment provides a mock function with given fields: donationComment
func (_m *DonationRepository) SaveComment(donationComment entities.DonationComment) (entities.DonationComment, error) {
	ret := _m.Called(donationComment)

	if len(ret) == 0 {
		panic("no return value specified for SaveComment")
	}

	var r0 entities.DonationComment
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.DonationComment) (entities.DonationComment, error)); ok {
		return rf(donationComment)
	}
	if rf, ok := ret.Get(0).(func(entities.DonationComment) entities.DonationComment); ok {
		r0 = rf(donationComment)
	} else {
		r0 = ret.Get(0).(entities.DonationComment)
	}

	if rf, ok := ret.Get(1).(func(entities.DonationComment) error); ok {
		r1 = rf(donationComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: donation
func (_m *DonationRepository) Update(donation entities.Donation) (entities.Donation, error) {
	ret := _m.Called(donation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Donation
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Donation) (entities.Donation, error)); ok {
		return rf(donation)
	}
	if rf, ok := ret.Get(0).(func(entities.Donation) entities.Donation); ok {
		r0 = rf(donation)
	} else {
		r0 = ret.Get(0).(entities.Donation)
	}

	if rf, ok := ret.Get(1).(func(entities.Donation) error); ok {
		r1 = rf(donation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDonationRepository creates a new instance of DonationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDonationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DonationRepository {
	mock := &DonationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
