// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositories

import (
	entities "capstone/entities"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *OrganizationRepository) FindAll() ([]entities.Organization, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Organization, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Organization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *OrganizationRepository) FindByID(id int) (entities.Organization, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entities.Organization, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entities.Organization); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Organization)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFundraisingByOrganizationID provides a mock function with given fields: id, limit, offset
func (_m *OrganizationRepository) FindFundraisingByOrganizationID(id int, limit int, offset int) ([]entities.Fundraising, error) {
	ret := _m.Called(id, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindFundraisingByOrganizationID")
	}

	var r0 []entities.Fundraising
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]entities.Fundraising, error)); ok {
		return rf(id, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []entities.Fundraising); ok {
		r0 = rf(id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Fundraising)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(id, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindVolunteersByOrganizationID provides a mock function with given fields: id, limit, offset
func (_m *OrganizationRepository) FindVolunteersByOrganizationID(id int, limit int, offset int) ([]entities.Volunteer, error) {
	ret := _m.Called(id, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindVolunteersByOrganizationID")
	}

	var r0 []entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]entities.Volunteer, error)); ok {
		return rf(id, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []entities.Volunteer); ok {
		r0 = rf(id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Volunteer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(id, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: organization
func (_m *OrganizationRepository) Save(organization entities.Organization) (entities.Organization, error) {
	ret := _m.Called(organization)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Organization) (entities.Organization, error)); ok {
		return rf(organization)
	}
	if rf, ok := ret.Get(0).(func(entities.Organization) entities.Organization); ok {
		r0 = rf(organization)
	} else {
		r0 = ret.Get(0).(entities.Organization)
	}

	if rf, ok := ret.Get(1).(func(entities.Organization) error); ok {
		r1 = rf(organization)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationRepository creates a new instance of OrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationRepository {
	mock := &OrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
