// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositories

import (
	entities "capstone/entities"

	mock "github.com/stretchr/testify/mock"
)

// VolunteerRepository is an autogenerated mock type for the VolunteerRepository type
type VolunteerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: volunteer
func (_m *VolunteerRepository) Create(volunteer entities.Volunteer) (entities.Volunteer, error) {
	ret := _m.Called(volunteer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Volunteer) (entities.Volunteer, error)); ok {
		return rf(volunteer)
	}
	if rf, ok := ret.Get(0).(func(entities.Volunteer) entities.Volunteer); ok {
		r0 = rf(volunteer)
	} else {
		r0 = ret.Get(0).(entities.Volunteer)
	}

	if rf, ok := ret.Get(1).(func(entities.Volunteer) error); ok {
		r1 = rf(volunteer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *VolunteerRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, limit
func (_m *VolunteerRepository) FindAll(page int, limit int) ([]entities.Volunteer, int, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Volunteer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]entities.Volunteer, int, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []entities.Volunteer); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Volunteer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindApplicationByVolunteerAndCustomer provides a mock function with given fields: volunteerID, customerID
func (_m *VolunteerRepository) FindApplicationByVolunteerAndCustomer(volunteerID uint, customerID uint) (entities.Application, error) {
	ret := _m.Called(volunteerID, customerID)

	if len(ret) == 0 {
		panic("no return value specified for FindApplicationByVolunteerAndCustomer")
	}

	var r0 entities.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (entities.Application, error)); ok {
		return rf(volunteerID, customerID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) entities.Application); ok {
		r0 = rf(volunteerID, customerID)
	} else {
		r0 = ret.Get(0).(entities.Application)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(volunteerID, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *VolunteerRepository) FindByID(id uint) (entities.Volunteer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (entities.Volunteer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) entities.Volunteer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Volunteer)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTop provides a mock function with given fields:
func (_m *VolunteerRepository) FindTop() ([]entities.Volunteer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindTop")
	}

	var r0 []entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Volunteer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Volunteer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Volunteer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: volunteer
func (_m *VolunteerRepository) Update(volunteer entities.Volunteer) (entities.Volunteer, error) {
	ret := _m.Called(volunteer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Volunteer) (entities.Volunteer, error)); ok {
		return rf(volunteer)
	}
	if rf, ok := ret.Get(0).(func(entities.Volunteer) entities.Volunteer); ok {
		r0 = rf(volunteer)
	} else {
		r0 = ret.Get(0).(entities.Volunteer)
	}

	if rf, ok := ret.Get(1).(func(entities.Volunteer) error); ok {
		r1 = rf(volunteer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, volunteer
func (_m *VolunteerRepository) UpdateByID(id uint, volunteer entities.Volunteer) (entities.Volunteer, error) {
	ret := _m.Called(id, volunteer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 entities.Volunteer
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, entities.Volunteer) (entities.Volunteer, error)); ok {
		return rf(id, volunteer)
	}
	if rf, ok := ret.Get(0).(func(uint, entities.Volunteer) entities.Volunteer); ok {
		r0 = rf(id, volunteer)
	} else {
		r0 = ret.Get(0).(entities.Volunteer)
	}

	if rf, ok := ret.Get(1).(func(uint, entities.Volunteer) error); ok {
		r1 = rf(id, volunteer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVolunteerRepository creates a new instance of VolunteerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolunteerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolunteerRepository {
	mock := &VolunteerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
